# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(default='', help_text='\u5934\u50cf', upload_to='img/avtar/'),
        ),
        migrations.AddField(
            model_name='actor',
            name='baidu_url',
            field=models.URLField(default='', help_text='\u767e\u5ea6\u94fe\u63a5\u5730\u5740', max_length=100),
        ),
    ]
