# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20161028_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(help_text='\u5934\u50cf', upload_to='img/avatar/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='baidu_url',
            field=models.URLField(help_text='\u767e\u5ea6\u767e\u79d1\u5730\u5740'),
        ),
    ]
