# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20161029_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='baidu_url',
            field=models.URLField(help_text='\u767e\u5ea6\u767e\u79d1\u5730\u5740', unique=True),
        ),
    ]
